POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "butter",
  "quantity": 4,
  "itemImage": "https://storcpdkenticomedia.blob.core.windows.net/media/lolretail/media/lolr-media/products/2022_salted_butter_product_800x800.png?ext=.png",
  "userId": 1
}