GET http://localhost:8080/recipes?userId=1
Accept: application/json

###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "userId": 1,
  "recipeImage": "https://www.foodnetwork.com/content/dam/images/food/fullset/2014/3/6/0/RF0104_From-Scratch-Pumpkin-Pie_s4x3.jpg",
  "items": [],
  "name": "Pumpkin pie"
}
###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "userId": 1,
  "recipeImage": "https://recipe30.com/wp-content/uploads/2020/11/Apple-pie.jpg",
  "items": [],
  "name": "apple pie"
}
###
